#ifndef UTILIDADES_H_INCLUDED
#define UTILIDADES_H_INCLUDED


/* Todo lo relacionado al menu */

void menu();
enum opciones {INGRESAR=1,LISTAR,ORDENAR_X_ANIO,ORDENAR_X_MATRICULA,BUSCAR,CALCULAR_PASAJERO,CALCULAR_ASIENTOS,BAJAR_ARCHIVO,SALIR};
enum verificar{SI,NO};
#endif // UTILIDADES_H_INCLUDED
