#ifndef UTILIDADES_H_INCLUDED
#define UTILIDADES_H_INCLUDED
void menu();
enum opciones {INGRESAR=1,LISTAR,ORDENAR_X_ANIO,ORDENAR_X_MATRICULA,BUSCAR,CALCULAR_PASAJERO,CALCULAR_ASIENTOS,BAJAR_ARCHIVO,SALIR};
void Error();
void Error1();
void presentacion();
#endif // UTILIDADES_H_INCLUDED
